"""Lossless, law-verified lenses between bead models and the ``layers`` schema.

Maps bead's corpus, annotation, and resource models to and from the canonical
``layers`` record models generated by ``lairs`` (``lairs.records``) via didactic
lenses (``dx.Lens``/``dx.Iso``): the layers view is a faithful, standalone
projection built from the generated models; the lens complement holds the
bead-only round-trip remainder. Round-trip fidelity is guaranteed by the
didactic GetPut/PutGet laws.

What is mapped:

- ``CorpusRecord`` to a layers ``expression`` (see ``bridges``).
- ``CorpusGraph`` to the layers property graph (expressions, graph nodes, and a
  ``graphEdgeSet``) bundled as a :class:`CorpusGraphLayers` view (see
  ``graph_lens``).
- a dependency parse to a layers ``tokenization`` with part-of-speech and
  dependency annotation layers bundled as a :class:`ParsedSentenceLayers` view
  (see ``parse_lens``).
- bead's resources to their layers counterparts: ``LexicalItem`` to an
  ``entry``, ``Lexicon`` to a ``collection``, and ``Template`` to a ``template``
  (see ``resource_lens``).
"""

from __future__ import annotations

from bead.interop.layers.bridges import (
    RECORD_EXPRESSION,
    RecordExpressionLens,
    record_to_expression,
)
from bead.interop.layers.graph_lens import (
    CORPUS_GRAPH_LAYERS,
    CorpusGraphLayers,
    CorpusGraphLayersLens,
    graph_to_layers,
)
from bead.interop.layers.parse_lens import (
    PARSED_SENTENCE_LAYERS,
    ParsedSentenceLayers,
    ParsedSentenceLayersIso,
    parse_to_layers,
)
from bead.interop.layers.resource_lens import (
    LEXICAL_ITEM_ENTRY,
    LEXICON_COLLECTION,
    TEMPLATE_LAYERS,
    LexicalItemEntryLens,
    LexiconCollectionLens,
    LexiconLayers,
    TemplateLayersLens,
)

__all__ = [
    "CORPUS_GRAPH_LAYERS",
    "LEXICAL_ITEM_ENTRY",
    "LEXICON_COLLECTION",
    "PARSED_SENTENCE_LAYERS",
    "RECORD_EXPRESSION",
    "TEMPLATE_LAYERS",
    "CorpusGraphLayers",
    "CorpusGraphLayersLens",
    "LexicalItemEntryLens",
    "LexiconCollectionLens",
    "LexiconLayers",
    "ParsedSentenceLayers",
    "ParsedSentenceLayersIso",
    "RecordExpressionLens",
    "TemplateLayersLens",
    "graph_to_layers",
    "parse_to_layers",
    "record_to_expression",
]
